language: node_js
dist: trusty
sudo: false
matrix:
  include:
  - env: PROJECT="api"
  - env: PROJECT="www"
  - env: PROJECT="packages/nusmoderator"
cache:
  yarn: true
  directories:
    - node_modules
    - api/node_modules
    - www/node_modules
    - packages/nusmoderator/node_modules
script:
  - yarn install && cd $PROJECT
  - npm run ci
after_success:
  cat ./www/coverage/lcov.info | ./www/node_modules/coveralls/bin/coveralls.js
